# Generated by Django 5.1.6 on 2025-02-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_trendingnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingnews',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
        migrations.AlterField(
            model_name='trendingnews',
            name='clicks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trendingnews',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
